/*
 place ={
 infowin_html: content of infowindow,
 tooltip_html: content of tooltip,
 position:{lat:latitude, lng:longitude}

 }
 */
var places = [];
places.push({ infowin_html: "<h3><a href='http://en.wikipedia.org/wiki/Oak_Park,_Illinois' target='_blank'>Oak Park, Illinois</a></h3><div><img src='http://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Habs_flw_oak_park_home.jpg/220px-Habs_flw_oak_park_home.jpg' width='220' hieght='174' /></div><div>Oak Park, Illinois is a suburb bordering the west side of the city of Chicago in Cook County, Illinois, United States. It is the twenty-fifth largest municipality in Illinois. Oak Park has easy access to downtown Chicago (the Chicago Loop) due to public transportation such as the Chicago 'L' Blue and Green lines, CTA buses, and Metra commuter rail. The 2000 census showed that the area had a total population of 52,524. As of the 2010 census, the population had dropped by 1.2 percent to 51,878.</div>", tooltip_html: "<h3>Oak Park, Illinois</h3><div><stong>Population:</strong> 52k</div>Click for more..", position: { lat: 41.883333, lng: -87.8 } });
places.push({ infowin_html: "<h3><a href='http://en.wikipedia.org/wiki/Chicago,_Illinois' target='_blank'>Chicago, Illinois</a></h3><div><img src='http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/20070909_Chicago_Half_Marathon.JPG/220px-20070909_Chicago_Half_Marathon.JPG' width='220' hieght='174' /></div><div>Chicago is the largest city in the U.S. state of Illinois and the third most populous city in the United States, with around 2.7 million residents. Its metropolitan area, sometimes called \"Chicagoland,\" is the third largest in the United States, with an estimated 9.8 million people in the states of Illinois, Wisconsin and Indiana. Chicago is the county seat of Cook County.</div>", tooltip_html: "<h3>Chicago, Illinois</h3><div><stong>Population:</strong> 2.7m</div>Click for more..", position: { lat: 41.881944, lng: -87.627778 } });
places.push({ infowin_html: "<h3><a href='http://en.wikipedia.org/wiki/Evanston,_Illinois' target='_blank'>Evanston, Illinois</a></h3><div><img src='http://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Aerial_View_of_Downtown_Evanston.jpeg/250px-Aerial_View_of_Downtown_Evanston.jpeg' width='220' hieght='165' /></div><div>Evanston is a suburban municipality in Cook County, Illinois 12 miles north of downtown Chicago, bordering Chicago to the south, Skokie to the west, and Wilmette to the north, with an estimated population of 74,360 as of 2003.[4] It is one of the North Shore communities that adjoin Lake Michigan. The boundaries of the city of Evanston are coterminous with those of Evanston Township – although school districts 65 and 202 take in a small portion of eastern Skokie. Evanston is the home of Northwestern University.</div>", tooltip_html: "<h3>Evanston, Illinois</h3><div><stong>Population:</strong> 74k</div>Click for more..", position: { lat: 42.04638, lng: -87.694608 } });
places.push({ infowin_html: "<h3><a href='http://en.wikipedia.org/wiki/Oak_Lawn,_Illinois' target='_blank'>Oak Lawn, Illinois</a></h3><div><img src='http://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/52nd_and_95th_oak_lawn.jpg/375px-52nd_and_95th_oak_lawn.jpg' width='250' hieght='160' /></div><div>Oak Lawn is a village in Cook County, Illinois, United States. The population was 55,245 at the 2000 census. Oak Lawn is a suburb of the city of Chicago, located southwest of the city. It shares borders with the city in two areas, but is surrounded mostly by other suburbs.</div>", tooltip_html: "<h3>Oak Lawn, Illinois</h3><div><stong>Population:</strong> 55k</div>Click for more..", position: { lat: 41.715, lng: -87.753333 } });